; Created:	2013-02-20	to recover the cme_mask image from the indices cme_mask_str (generated by cme_mask_inds.pro)

; Last edited:	2013-02-25	from Huw's email to use pointers instead of structures.

function cme_mask_recover, cme_mask_str

ncme = n_elements(cme_mask_str.npoints)

im = intarr(cme_mask_str.size)

for i=0,ncme-1 do begin
	im[*cme_mask_str.cmeptr[i]] = i+1
endfor

return, im

end
